isoko/Models/DAL/Payment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace isoko.Models.DAL
{
    public class Payment : IPayment
    {
        private readonly IsokopayContext context;

        public Payment(IsokopayContext context)
        {
            this.context = context;
        }
        public MerchantPayment Add(MerchantPayment merchantPayment)
        {
            context.MerchantPayment.Add(merchantPayment);
            context.SaveChanges();
            return merchantPayment;
        }
    }
}

isoko/Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using isoko.Common;
using isoko.Models;
using isoko.Models.DAL;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using X.PagedList;
using static isoko.Models.ApplicationViewModel;

namespace isoko.Controllers
{
    public class PaymentController : Controller
    {
        private IsokopayContext _db;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private IRepository<MerchantPayment> interfaceObj;
        public PaymentController(IsokopayContext db, IHttpContextAccessor httpContextAccessor)
        {
            _db = db;
            _httpContextAccessor = httpContextAccessor;
            this.interfaceObj = new Repository<MerchantPayment>();
        }
        public IActionResult Index(string currentFilter, string Status, string search, int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            var payment = _db.MerchantPayment.ToList();

            if(Status == "UserEmail")
            {
                payment = payment.Where(s => s.UserEmail.StartsWith(search)).ToList();
                return View(payment.ToPagedList(pageNumber, pageSize));
            }
            if(Status == "OrderId")
            {
                int orderId = Convert.ToInt32(search);
                payment = payment.Where(s => s.OrderId == orderId).ToList();
                return View(payment.ToPagedList(pageNumber, pageSize));
            }
            return View(payment.ToPagedList(pageNumber, pageSize));
        }
        [HttpGet]
        public IActionResult Payment(long Id)
        {
            
            var Payment = _db.MerchantPayment.Find(Id);
            double? Total = Payment.TotalPrice + Payment.IsokopayFee;
            Payment.TotalPrice = Total;

            MerchantViewModel model = new MerchantViewModel();
            model.MerchantName = Payment.MerchantName;
            model.OrderId = Payment.OrderId;
            model.Email = Payment.UserEmail;
            model.Product = Payment.Product;
            model.TotalPrice = Total;
            return View(model);
        }
        [HttpPost]
        public IActionResult Payment(MerchantViewModel model)
        {
            var mp = _db.MerchantPayment.OrderByDescending(x => x.Id).FirstOrDefault(x => x.OrderId == model.OrderId);
            mp.Status = (int)MyEnums.ShopOrderStatus.Done;
            interfaceObj.UpdateModel(mp);
            interfaceObj.Save();
            PaymentViewModel vm = new PaymentViewModel();
            vm.orderid = mp.OrderId;
            vm.paymentstatus =(int) MyEnums.ShopOrderStatus.Done;
            vm.shippingstatus =(int) MyEnums.ShopOrderStatus.Done;
            string myJson = JsonConvert.SerializeObject(vm);
            string resp = Post(myJson);

            if (resp.Length > 0)
            {
                TempData["successmessage"] = "Saved successfully";
                return RedirectToAction(nameof(Index));
            }
            else
            {
                TempData["successmessage"] = "Encountered An Error";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        public string Post(string myJson)
        {
            string response = "";
            string url = "http://198.38.85.25:1234/s-cart/public/api/status";
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(url);
            request.Method = "POST";
            request.ContentType = "application/json";
            request.ContentLength = myJson.Length;
            using (Stream webStream = request.GetRequestStream())
            using (StreamWriter requestWriter = new StreamWriter(webStream, System.Text.Encoding.ASCII))
            {
                requestWriter.Write(myJson);
            }

            try
            {
                WebResponse webResponse = request.GetResponse();
                using (Stream webStream = webResponse.GetResponseStream() ?? Stream.Null)
                using (StreamReader responseReader = new StreamReader(webStream))
                {
                    response = responseReader.ReadToEnd();  
                }
            }
            catch (Exception e)
            {
                
            }
            return response;
        }

    }
}

isoko/Views/Payment/Index.cshtml
@model IPagedList<isoko.Models.MerchantPayment>
@using X.PagedList;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_admin.cshtml";
}

@{
    var message = TempData["successmessage"] ?? string.Empty;
}

<div class="panel panel-success">
    <div class="panel-heading">
        <h3 class="panel-title">Search</h3>
    </div>
    <div class="panel-body">
        @using (Html.BeginForm("Index", "Payment", FormMethod.Get))
        {
            @Html.DropDownList("Status", new List<SelectListItem>

            {
                new SelectListItem {Text = "Email", Value = "UserEmail"},
                new SelectListItem {Text = "OrderId", Value = "OrderId"},
            }, new { @class = "form-control", style = "width:333px" })
            <br />
            @Html.TextBox("Search", null, new { @class = "form-control", style = "width:333px" })
            <br />
            <input type="submit" class="btn btn-success" value="Search">
        }
    </div>
</div>
<table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>
                Merchant Name
            </th>
            <th>
                Order Id
            </th>
            <th>
                User Email
            </th>
            <th>
                Product
            </th>
            <th>
                Unit Price
            </th>
            <th>
                Quantity
            </th>
            <th>
                Isokopay Fee
            </th>
            <th>
                Shipping
            </th>
            <th>
                Status
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MerchantName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserEmail)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UnitPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsokopayFee)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Shipping)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    <a asp-action="Payment" asp-route-id="@item.Id">Make Payment</a>
            </tr>
        }
    </tbody>
</table>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
<script type="text/javascript">
    var message = '@message';
    if(message)
        alert(message);
</script>

isoko/Views/Payment/Payment.cshtml
@model isoko.Models.ApplicationViewModel.MerchantViewModel

@{
    ViewData["Title"] = "Payment";
    Layout = "~/Views/Shared/_admin.cshtml";
}

<h2>Make Payment</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Payment">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MerchantName" class="control-label"></label>
                <input asp-for="MerchantName" class="form-control" readonly/>
                <span asp-validation-for="MerchantName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OrderId" class="control-label"></label>
                <input asp-for="OrderId" class="form-control" readonly/>
                <span asp-validation-for="OrderId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" readonly/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product" class="control-label"></label>
                <input asp-for="Product" class="form-control" readonly/>
                <span asp-validation-for="Product" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalPrice" class="control-label"></label>
                <input asp-for="TotalPrice" class="form-control" readonly/>
                <span asp-validation-for="TotalPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Make Payment" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>