isoko/Controllers/ReportsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using isoko.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;

namespace isoko.Controllers
{
    public class ReportsController : Controller
    {
        private IsokopayContext _db;
        private readonly IHttpContextAccessor _httpContextAccessor;

        public ReportsController(IsokopayContext db, IHttpContextAccessor httpContextAccessor)
        {
            _db = db;
            _httpContextAccessor = httpContextAccessor;
        }
        public IActionResult Index(string currentFilter, string Status, string search, int? page)
        {
            int pageSize = 10;
            int pageNumber = (page ?? 1);
            var userId = _httpContextAccessor.HttpContext.User.Identity.Name;
            var usrs = _db.AspNetUsers.OrderByDescending(x => x.Id).FirstOrDefault(x => x.UserName == userId);

            if(Status == null)
            {
                if(usrs.UserType == "Admin")
                {
                    var ussr = _db.MerchantPayment.ToList();
                    return View(ussr.ToPagedList(pageNumber, pageSize));
                }
                if (usrs.UserType == "Merchant")
                {
                    var ussr = _db.MerchantPayment.Where(x => x.UserEmail == usrs.Email);
                    return View(ussr.ToPagedList(pageNumber, pageSize));
                }
                if (usrs.UserType == "PSP")
                {
                    var ussr = _db.MerchantPayment.ToList();
                    return View(ussr.ToPagedList(pageNumber, pageSize));
                }
            }
            if (Status == "5")
            {
                if (usrs.UserType == "Admin")
                {
                    var ussr = _db.MerchantPayment.Where(x=>x.Status == 5).ToList();
                    return View(ussr.ToPagedList(pageNumber, pageSize));
                }
                if (usrs.UserType == "Merchant")
                {
                    var ussr = _db.MerchantPayment.Where(x => x.UserEmail == usrs.Email && x.Status == 5);
                    return View(ussr.ToPagedList(pageNumber, pageSize));
                }
                if (usrs.UserType == "PSP")
                {
                    var ussr = _db.MerchantPayment.Where(x => x.Status == 5).ToList();
                    return View(ussr.ToPagedList(pageNumber, pageSize));
                }
            }
            else
            {
                if (usrs.UserType == "Admin")
                {
                    var ussr = _db.MerchantPayment.ToList();
                    return View(ussr.ToPagedList(pageNumber, pageSize));
                }
                if (usrs.UserType == "Merchant")
                {
                    var ussr = _db.MerchantPayment.Where(x => x.UserEmail == usrs.Email);
                    return View(ussr.ToPagedList(pageNumber, pageSize));
                }
                if (usrs.UserType == "PSP")
                {
                    var ussr = _db.MerchantPayment.ToList();
                    return View(ussr.ToPagedList(pageNumber, pageSize));
                }
            }
            
            return View();
        }
    }
}

isoko/Views/Reports/Index.cshtml
@model IPagedList<isoko.Models.MerchantPayment>
@using X.PagedList;
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_admin.cshtml";
}

<div class="panel panel-success">
    <div class="panel-heading">
        <h3 class="panel-title">Search</h3>
    </div>
    <div class="panel-body">
        @using (Html.BeginForm("Index", "Reports", FormMethod.Get))
        {
            @Html.DropDownList("Status", new List<SelectListItem>

            {
                new SelectListItem {Text = "Paid", Value = "5"},
                new SelectListItem {Text = "Unpaid", Value = "1"},
            }, new { @class = "form-control", style = "width:333px" })
            
            <br />
            <input type="submit" class="btn btn-success" value="Search">
        }
    </div>
</div>

<table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
        <tr>
            <th>
                Merchant Name
            </th>
            <th>
                Order Id
            </th>
            <th>
                Email
            </th>
            <th>
                Product
            </th>
            <th>
                Unit Price
            </th>
            <th>
                Quantity
            </th>
            <th>
                Isokopay Fee
            </th>

            <th>
                Status
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.MerchantName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserEmail)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UnitPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IsokopayFee)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
            </tr>
        }
    </tbody>
</table>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount